
# --- CD-PPO specific parameters ---

action_selector: "multinomial"
epsilon_start: .0
epsilon_finish: .0
epsilon_anneal_time: 100000
mask_before_softmax: True

runner: "parallel"

buffer_size: 8
batch_size_run: 8
batch_size: 8
# accumulated_episodes: 8

mac: 'mappo_mac'
agent: 'n_rnn'
actor_input_seq_str: 'o_la'

lr: 0.0005
critic_coef: 0.5
entropy_coef: 0.001
reg_coef: 0.01
gae_lambda: 0.95
mini_epochs: 4
eps_clip: 0.2
save_probs: True

agent_output_type: "pi_logits"
learner: "cdppo_learner"
critic_type: "mappo_rnn_critic"
critic_input_seq_str: 'o_la^i'

use_layer_norm: True
use_orthogonal: True
gain: 0.01
use_value_norm: True

name: "cdppo_lt"
train_with_joint_data: False
n_decoupled_iterations: 2
max_individual_envs: 0.2
fake_dynamics_prob: 0.15
select_ls_randomly: True
use_zero_like_context : False
aug_type: 'noise'

run: "cdppo_run"