# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000
mask_before_softmax: True

runner: "parallel"

buffer_size: 2500
batch_size_run: 8
batch_size: 8

# update the target network every {} training steps
target_update_interval: 200

lr: 0.0005
critic_lr: 0.0005
td_lambda: 0.6
entropy_coef: 0.01

obs_individual_obs: False
obs_last_action: False
obs_agent_id: False

# use COMA
agent_output_type: "pi_logits"
learner: "coma_learner"
critic_type: "coma_critic"
critic_q_fn: "coma"
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
q_nstep: 5  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

name: "coma"
run: "mappo_run"