env_args:
  key: "replenishment_efficient_env-v0"
  n_agents: 50
  task_type: "sku50.multi_store.standard"
  mode: train
  time_limit: 100
test_interval: 8000
log_interval: 8000
runner_log_interval: 8000
learner_log_interval: 8000

action_selector: "multinomial"
epsilon_start: .0
epsilon_finish: .0
epsilon_anneal_time: 100000
mask_before_softmax: True

runner: "parallel"

buffer_size: 8
batch_size_run: 8
batch_size: 8
# accumulated_episodes: 8

mac: 'mappo_mac'
# agent: 'mlp' #n_rnn
agent: 'n_rnn'
hidden_dim: 128
actor_input_seq_str: 'o_la'

obs_agent_id: False

# lr: 0.0005
# critic_coef: 0.5
# entropy_coef: 0.01
# gae_lambda: 0.95
# mini_epochs: 4
# eps_clip: 0.2
# save_probs: True

lr: 0.0005
critic_coef: 0.5
entropy_coef: 0.001 #0.001
reg_coef: 0.01
gamma: 0.985
gae_lambda: 0.95
mini_epochs: 4
eps_clip: 0.2
save_probs: True

agent_output_type: "pi_logits"
learner: "ppo_learner"
# critic_type: "mlp_critic"
critic_type: "mappo_rnn_critic"
critic_input_seq_str: 'o_la^i'

use_layer_norm: True #True
use_orthogonal: True #True
# dropout: False
gain: 0.01
use_value_norm: True
use_zero_like_context: True
use_individual_rewards: True
use_mean_team_reward: True

name: "ippo"

## add
train_with_joint_data: False
n_decoupled_iterations: 1
max_individual_envs: 10
fake_dynamics_prob: 0.15
select_ls_randomly: True
aug_type: 'noise'

# wandb_project_name: "eff_replenishment_ippo_c20000_400_100"
# wandb_project_name: "eff_replenishment_ippo_debug"
# wandb_project_name: "eff_replenishment_ippo_sync_c_5000"
# wandb_project_name: "eff_replenishment_ippo_sync_c_20000"
# wandb_project_name: "eff_replenishment_ippo_train_300_c_5000"
# wandb_project_name: "eff_replenishment_ippo_train_rand_c_20000"

run: "mappo_run"