# --- CENTRALV specific parameters ---
# Independent PPO with value norm, layer_norm, orthogonal, value clip
# but, without death agent mask, data chunk

action_selector: "multinomial"
epsilon_start: .0
epsilon_finish: .0
epsilon_anneal_time: 100000
mask_before_softmax: True

runner: "parallel"

buffer_size: 8
batch_size_run: 8
batch_size: 8
# accumulated_episodes: 8

mac: 'mappo_mac'
agent: 'n_rnn'
actor_input_seq_str: 'o_la'

obs_agent_id: False

lr: 0.0005
critic_coef: 0.5
entropy_coef: 0.01
gae_lambda: 0.95
mini_epochs: 4
eps_clip: 0.2
save_probs: True

agent_output_type: "pi_logits"
learner: "ppo_learner"
critic_type: "deepset_critic"
critic_input_seq_str: 'o_la^i'

use_layer_norm: True
use_orthogonal: True
gain: 0.01
use_value_norm: True

name: "mfppo"
wandb_project_name: "old_replenishment"

run: "mappo_run"